config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get 'home/index' => 'home#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
  resources :users, only: [:index, :edit, :update]

  root 'welcome#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :proficiencies
	has_many :users, through: :proficiencies
end

app/models/proficiency.rb
class Proficiency < ActiveRecord::Base
	belongs_to :user
	belongs_to :language
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_messageable


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "http://unlike.net/assets/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  has_many :proficiencies
  has_many :languages, through: :proficiencies

def self.filter(query)
    query.blank? ? User.all : User.where("lower(first_name) || lower(last_name) || lower(location) LIKE '%#{query.downcase}%'")
end

  def get_languages
    languages = []
    languages << "English #{self.english}" if self.english != "Not Interested"
    languages << "Spanish #{self.spanish}" if self.spanish != "Not Interested"
    languages << "French #{self.french}" if self.french != "Not Interested"
    languages << "Italian #{self.italian}" if self.italian != "Not Interested"
    languages << "German #{self.german}" if self.german != "Not Interested"
    languages
  end

def mailboxer_email(object)
  #Check if an email should be sent for that object
  #if true
  return "define_email@on_your.model"
  #if false
  #return nil
end
  	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from ActiveRecord::RecordNotFound do
		flash[:warning] = 'Resource not found.'
		redirect_back_or root_path
	end

	def after_sign_out_path_for(users)
		root_path
	end

	def after_sign_in_path_for(users)
	    home_index_path
	end

    def after_sign_up_path_for(users)
      edit_user_path(current_user)
    end

	def redirect_back_or(path)
		redirect_to request.referer || path
	end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index]
  before_action :get_box, only: [:index]
  before_action :get_conversation, except: [:index, :empty_trash]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
   
    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end
 
  def show
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end
   
  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  private

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
 
  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = get_users
		@user = current_user
	end

	def get_users 
		users = []
		languages = current_user.get_languages
		User.all.shuffle.each do |user|
			languages.each do |language|
				if (user.get_languages.join(',').include?(language)) && (user != current_user)
					users << user
					break
				end
			end
			break if users.size == 3
		end
		users
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
 
  def new
    @chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
  end
 
  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent!"
    redirect_to conversation_path(conversation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  
  def after_sign_in_path_for(users)
    home_index_path
  end

    def after_sign_up_path_for(users)
      edit_user_path(current_user)
    end


  before_filter :configure_permitted_parameters


  # my custom fields are :name, :heard_how
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, 
        :email, :password, :password_confirmation, :location, 
        :avatar, :about_me)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :current_password,
        :email, :password, :password_confirmation, :location, :avatar, :about_me)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.filter(params[:q]).paginate(page: params[:page], per_page: 10)
		render :partial => 'users' if request.xhr?
	end

	def edit
		@user = current_user
	end
	def update
		@user = current_user
		@user.update_attributes(params["user"].permit(:english, :spanish, :italian, :german, :french))

		redirect_to home_index_path
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  	if current_user
  		redirect_to home_index_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    s = ''
    #TODO(jason)- figure out how not to have the user added
    User.all.each do |user|
    	if current_user.id != user.id
      		s << "<option value='#{user.id}' #{'selected' if user == chosen_recipient}>#{user.first_name}</option>"
      	end
    end
    s.html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation) %>
 
<div class="btn-group-vertical pull-right">
  <% if conversation.is_trashed?(current_user) %>
    <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
  <% else %>
  	  	<%= link_to image_tag("trashcan.png", size: "30x30"), conversation_path(conversation), method: :delete, 
            data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>
 
  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
<% end %>

app/views/conversations/index.html.erb
<div class="container background">
  <div class="row titlebar">
    <div row="container row_1_conversations">
      <div class="col-xs-4 col-sm-4">
        <h4>YOUR CONVERSATIONS </h4>
      </div>

      <div class="col-xs-8 col-sm-8">
        <%=link_to 'NEW MESSAGE', new_message_path, class: 'btn btn-lg btn-primary btn-sm btn-new-conversation' %>
      </div>
    </div>
  </div>

  <div class="row messages_all">
    <div row="container">
      <div class="col-xs-4 col-sm-4">
          <ul class="nav nav-pills nav-stacked mailbox_options">
            <li><%= mailbox_section 'inbox', @box %></li>
            <li><%= mailbox_section 'sent', @box %></li>
            <li><%= mailbox_section 'trash', @box %></li>
          </ul>
      </div>

      <div class="col-xs-8 col-sm-8">
        <div class="pop_up">
            <% if @box == 'trash' %>
            <%= link_to image_tag("trashcan.png", size: "30x30"), empty_trash_conversations_path, class: 'icon', method: :delete,
                  data: {confirm: 'Are you sure?'} %></p>
            <% end %>

            <ul class="list-group no_message_box">
              <% if @conversations.empty? %>
                <h6>NO MESSAGES TO DISPLAY</h6>
              <% else %>
              <%= render partial: 'conversations/conversation', collection: @conversations %>
              <% end %>
            </ul>
          </div>
      </div>
    </div>
  </div>
  <%= will_paginate %>
</div>

app/views/conversations/show.html.erb
<br/>
<br/>

<div class="panel panel-default panel-default-conversation">
  <div class="panel-heading-large"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>
          <div class="media-left">
            <a><%= image_tag message.sender.avatar.url(:medium), :class =>'conversation_pic' %></a>
          </div>

          <div class="media-body">
            <h6 class="media-heading"><%= message.sender.first_name %></h6>
              <h7 class="blue-time"><%= time_ago_in_words(message.created_at) %> ago</h7> <br/>
          </div>

          <div class="messages-body"><%= message.body %></div>
          <div class="line-separator"></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group form-group-conversation">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control form-control-conversation', placeholder: 'Type something...', required: true %>
    <%= submit_tag "Send Message", class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/home/_display.html.erb
<a><%= image_tag user.avatar.url(:medium), :class =>'profile_pic' %></a>
<div>
  <h4 class="profile-heading"><%= user.first_name %>  <%= user.last_name %><br/><small> <%= user.location %></small></h4>
  <% user.get_languages.each do |language| %>
  <span class="label label-primary language-tags"><%= language %></span>
  <% end %><br/>
  <div class="About Me"><%= user.about_me %></div>
  <a><%= link_to "Message This User", new_message_path(:to => user.id), class: "btn btn-large btn-warning message-button " %></a>
</div>

    

app/views/home/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span> close </button>
        <h4 class="modal-title" id="myModalLabel">Language Preferences</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for user do |f| %>
        <%= f.input :english, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
        <%= f.input :spanish, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' }  %>
        <%= f.input :french, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
        <%= f.input :italian, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
        <%= f.input :german, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
      </div>
      <div class="modal-footer">
      <%= button_tag(type: 'submit', class: "btn btn-primary edit-language-btn") do %>
        <i class="icon-ok icon-white"></i>Update 
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!--#page with 3 people to message -->
<div class="jumbotron jumbotron-home">
  <div class="container home">
    <div class="page-header">
    <h17>Welcome to Chatable <br \>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-lg btn-primary blue-btn" data-toggle="modal" data-target="#myModal">
  Update Languages
</button>
    </div>
  </div>
</div>
<br \>

<div class="container user_table">
  <div class="row">
		<% @users.each do |user| %>
      <div class="col-sm-4">
			    <li class="random-users"><%= render partial: "display", locals: {user: user, languages: user.languages} %></li><br \>
          </div>
		<% end %>
  </div>
</div>

<%= render partial: 'modal', locals: {user: @user} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>chatable</title>
<%= stylesheet_link_tag   'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

	
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top navbar_without_border">
		<div class="container">
			<!--p class="notice"><%= notice %></p-->
			<!--p class="alert"><%= alert %></p-->
			<!--nav class="navbar navbar-inverse"-->
			<!--div class="container"-->
			<div class="navbar-header">
				<%= link_to 'chatable', root_path, class: 'chatable'%>
			</div>  
			<ul class="navbar_categories">
				<% if user_signed_in? %>
				<li class="toolbarcategories"><%= link_to 'EDIT PROFILE', edit_user_registration_path %></li>
				<li class="toolbarcategories"><%= link_to 'FIND PALS', users_path %></li>
				<li class="toolbarcategories"><%= link_to 'YOUR MESSAGES', conversations_path %></li>
				<li class="toolbarcategories"><%= link_to 'LOG OUT', destroy_user_session_path, method: :delete %></li>
				<% else %>
				<li class="toolbarcategories"><%= link_to 'SIGN UP', new_user_registration_path %> </li>
				<li class="toolbarcategories"><%= link_to 'LOG IN', new_user_session_path %></li>
				<% end %>
			</ul>
		</div>
	</nav>
	<%= yield %>
</body>
</html>

app/views/messages/new.html.erb
<%= form_tag messages_path, :method => :post do %>
<div class="container new-message">
  <h4> NEW MESSAGE </h4>
  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject'%>
    <br />
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= label_tag 'recipients', 'Choose Recipients' %>
    <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, class: 'form-control chosen-it', required: true, "data-placeholder" => " " %>
  </div>
  <%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/users/_display.html.erb
<a><%= image_tag user.avatar.url(:medium), :class =>'profile_pic' %></a>
<div>
  <h4 class="profile-heading"><%= user.first_name %>  <%= user.last_name %><br/><small> <%= user.location %></small></h4>
  <% user.get_languages.each do |language| %>
  <span class="label label-primary language-tags"><%= language %></span>
  <% end %><br/>
  <div class="About Me"><%= user.about_me %></div>
  <a><%= link_to "Message This User", new_message_path(:to => user.id), class: "btn btn-large btn-warning message-button " %></a>
</div>

    

app/views/users/_users.html.erb
<div class="container user_table with_border">
  <div class="row">
    <% @users.each do |user| %>
    <% if user != current_user %>
      <div class="col-sm-4 pad-bottom">
          <li class="random-users"><%= render partial: "display", locals: {user: user, languages: user.languages} %></li><br \>
          </div>
          <% end %>
     <% end %>
  </div>
</div>

<ul class="pager">
<%= will_paginate @users, page_links: false, container: false %>
</ul>

app/views/users/edit.html.erb
<!--<%= form_for(@user, action: "/users/#{@user.id}", method: :put) do |f| %>

<div class="field">
	<%= f.label :english %><br />
	<%= f.select :english, options_for_select(%w[0 1 2 3 4 5]) %>
</div>
<div class="field">
    <%= f.label :spanish %><br />
	<%= f.select :spanish, options_for_select(%w[0 1 2 3 4 5]) %>
</div>
<div class="field">
	<%= f.label :french %><br />
	<%= f.select :french, options_for_select(%w[0 1 2 3 4 5]) %>
</div>
<div class="field">
	<%= f.label :italian %><br />
	<%= f.select :italian, options_for_select(%w[0 1 2 3 4 5]) %>
</div>
<div class="field">
	<%= f.label :german %><br />
	<%= f.select :german, options_for_select(%w[0 1 2 3 4 5]) %>
</div>
    <%= f.submit %>
<% end %>-->



<div class="language-header">
   <h1 class="language-edit">Language Settings
      <small>Select your skill level</small>
   </h1>
</div>
<div class="edit-language-form">
<%= simple_form_for @user do |f| %>
  <%= f.input :english, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
  <%= f.input :spanish, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' }  %>
  <%= f.input :french, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
  <%= f.input :italian, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
  <%= f.input :german, :prompt => "Set your skill level", :collection => ["Not Interested", "Beginner", "Intermediate", "Advanced", "Native Speaker"], wrapper_html: { class: 'language' } %>
   <%= button_tag(type: 'submit', class: "btn btn-primary edit-language-btn") do %>
    <i class="icon-ok icon-white"></i> Update
  <% end %>
<% end %>
</div>

app/views/users/index.html.erb
<!--page to search through all the users -->

<div>
<%= form_tag "/users", method: 'GET', class: ' form-inline users_search' do %> 
<%= text_field_tag 'q', params[:q], placeholder: "Search name or location" %>
<div style="clear: both">
	<% end %>
</div>
</div>

<br/><br/>
<div id= "users">
	<%= render "users" %>
</div>

	

app/views/welcome/index.html.erb
<!--#page for people who have not signed up/in yet-->

<div class="jumbotron jumbotron-main">
  <div class="container">
      <h1>chatable</h1>
      <h3>connecting a diverse world through <br \>online messaging, one language at a time...</h3>
  </div>
</div>

<div class="container_1">
  <div class="row_one">
  	INTRODUCING CHATABLE
  </div><br \>
  <div class="row_one_second">
  	The most effective way to expand your network, find new friends <br \>
  	and learn a new language - all from the comfort of your own home!
  </div>
  <br \> <br \> 
  <div class="row_one_third">
    <div class="col-xs-6 col-sm-4">
    	<%= image_tag 'signin.jpg', :class => "display-img" %>
    	 <br \>
     	<h7 class="home-title"> FIND NEW PEOPLE </h7>
      <br \> 
      <h8> Search for new people to chat with online using our search feature! Choose people to speak with based upon their interests, spoken languages and personal profile. </h8>
    </div>
    <div class="col-xs-6 col-sm-4">
    	 <%= image_tag 'newlanguage.jpg', :class => "display-img" %>
       <br \>
      	<h7 class="home-title">LEARN NEW LANGUAGES</h7> <br \>
        <h8>Message other users in any language, from anywhere in the world. Indicate your starting language proficiency to better improve upon your skills. Then, chat away! </h8>
    </div>
    <div class="col-xs-6 col-sm-4">
    	<%= image_tag 'newhorizons.jpg', :class => "display-img" %>
       <br \>
    	<h7 class="home-title">REACH NEW HEIGHTS</h7> <br \>
      <h8 class="text-justify">Master your language skills and gain a deeper appreciation for other cultures by building relationships with people from all over the world.</h8>
    </div>
  </div>
 </div>

<br \><br \><br \><br \>

<div class="jumbotron jumbotron-second">
  <div class="container">
    <!--filler text-->
  </div>
</div>

<div class="container_2">
  <div class="row_two">
  HOW DOES IT WORK?
  </div>
  	<br \>
  <div class="row_two_categories">
    <div class="col-xs-6 col-sm-3">
     	SIGN UP
     	<%= image_tag 'computer.png', :class => "display-img2" %>
      <br \>
      <h10> </h10>
    </div>
    <div class="col-xs-6 col-sm-3">
      	MAKE NEW FRIENDS
      	<%= image_tag 'user.png', :class => "display-img2" %>
        <br />
        <h10> </h10>
    </div>
    <div class="col-xs-6 col-sm-3">
    	MASTER YOUR SKILLS
    	<%= image_tag 'language.png', :class => "display-img2" %>
      <br />
        <h10> </h10>
    </div>
    <div class="col-xs-6 col-sm-3">
    	SEE THE WORLD
    	<%= image_tag 'world.png', :class => "display-img2" %>
        <br />
        <h10> </h10>
    </div>
  </div>
</div>

<div class="container_4">
  <br \>
  <div class="row_four">
    Join the Movement <br \>
    <%=link_to 'SIGN UP', new_user_registration_path, class: 'btn btn-lg btn-primary btn-sm btn-to-signup' %>
    <%=link_to 'LOG IN', new_user_session_path, class: 'btn btn-lg btn-primary btn-sm btn-to-signup' %>
    <br />
  </div>
</div>